what is function transformer in machine learning ?

The Function Transformer is a tool in scikit-learn, a popular
Python library for machine learning, that allows you to apply a
specified function to the input data. The Function Transformer
can be useful for performing custom transformations of input
data in a machine learning pipeline.

In [35]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [36]:
# create a dataset
X = np.array([[1, 2], [3, 4]])

# define the transformation function
log_transform = FunctionTransformer(np.log1p)

# apply the transformation to the dataset
X_transformed = log_transform.transform(X)

# view the transformed data
print(X_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [37]:
x=np.array([[1,2],[3,4]])
def squ(x):
  return np.hstack((x,x**2))
# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(squ)

# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [38]:
#Array range(21-50)  even numbers filter  --> function transofrmer --->

x=np.arange(21,51).astype(int)
def even(x):
  return x[x%2==0]
a = FunctionTransformer(even)
hi = a.transform(x)
print(hi)



[22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [39]:
# create a dataset
X = np.array([[1, 2], [3, 4]])

# define a custom scaling function
def my_scaling(X):
  return X / np.max(X)

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(my_scaling)

# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [40]:
#Data cleaning
X=np.array([[1,2],[3,np.nan]])

def my_cleaning(X):
  X[np.isnan(X)] = 0
  return X

# create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(my_cleaning)

# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)

[[1. 2.]
 [3. 0.]]


In [41]:
import pandas as pd
import numpy as np

In [42]:
df=pd.read_csv("/content/insurance - insurance.csv")

In [43]:
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [44]:
from sklearn.preprocessing import LabelEncoder

In [45]:
lb=LabelEncoder

In [46]:
lb = LabelEncoder()
df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['region']=lb.fit_transform(df['region'])

In [47]:
df

age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]

In [48]:
from sklearn.preprocessing import FunctionTransformer


In [49]:
x = df.drop(columns = ['charges'])
y = df['charges' ]

In [52]:
log_transform = FunctionTransformer(np.log1p)

# apply the transformation to the dataset
X_transformed = log_transform.transform(x)

In [51]:
X_transformed

age       sex       bmi  children    smoker    region
0     2.995732  0.000000  3.363842  0.000000  0.693147  1.386294
1     2.944439  0.693147  3.548755  0.693147  0.000000  1.098612
2     3.367296  0.693147  3.526361  1.386294  0.000000  1.098612
3     3.526361  0.693147  3.165686  0.000000  0.000000  0.693147
4     3.496508  0.693147  3.397189  0.000000  0.000000  0.693147
...        ...       ...       ...       ...       ...       ...
1333  3.931826  0.693147  3.464798  1.386294  0.000000  0.693147
1334  2.944439  0.000000  3.494080  0.000000  0.000000  0.000000
1335  2.944439  0.000000  3.633631  0.000000  0.000000  1.098612
1336  3.091042  0.000000  3.288402  0.000000  0.000000  1.386294
1337  4.127134  0.000000  3.403528  0.000000  0.693147  0.693147

[1338 rows x 6 columns]

In [54]:
df=pd.read_csv("/content/covid_toy.csv")

In [55]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [56]:
df=df.dropna()

In [57]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [59]:
from sklearn.preprocessing import LabelEncoder

In [60]:
lb = LabelEncoder()
df['gender']=lb.fit_transform(df['gender'])
df['cough']=lb.fit_transform(df['cough'])
df['city']=lb.fit_transform(df['city'])
df['has_covid']=lb.fit_transform(df['has_covid'])

/tmp/ipython-input-246397668.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender']=lb.fit_transform(df['gender'])
/tmp/ipython-input-246397668.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cough']=lb.fit_transform(df['cough'])
/tmp/ipython-input-246397668.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stab

In [61]:
df

age  gender  fever  cough  city  has_covid
0    60       1  103.0      0     2          0
1    27       1  100.0      0     1          1
2    42       1  101.0      0     1          0
3    31       0   98.0      0     2          0
4    65       0  101.0      0     3          0
..  ...     ...    ...    ...   ...        ...
95   12       0  104.0      0     0          0
96   51       0  101.0      1     2          1
97   20       0  101.0      0     0          0
98    5       0   98.0      1     3          0
99   10       0   98.0      1     2          1

[90 rows x 6 columns]

In [71]:
ft = FunctionTransformer(np.sqrt)

sq = ft.transform(df)

print(sq)

         age  gender      fever  cough      city  has_covid
0   7.745967     1.0  10.148892    0.0  1.414214        0.0
1   5.196152     1.0  10.000000    0.0  1.000000        1.0
2   6.480741     1.0  10.049876    0.0  1.000000        0.0
3   5.567764     0.0   9.899495    0.0  1.414214        0.0
4   8.062258     0.0  10.049876    0.0  1.732051        0.0
..       ...     ...        ...    ...       ...        ...
95  3.464102     0.0  10.198039    0.0  0.000000        0.0
96  7.141428     0.0  10.049876    1.0  1.414214        1.0
97  4.472136     0.0  10.049876    0.0  0.000000        0.0
98  2.236068     0.0   9.899495    1.0  1.732051        0.0
99  3.162278     0.0   9.899495    1.0  1.414214        1.0

[90 rows x 6 columns]


0     0
1     1
2     0
3     0
4     0
     ..
95    0
96    1
97    0
98    0
99    1
Name: has_covid, Length: 90, dtype: int64